# Generated by Django 3.2.5 on 2022-06-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20220621_2119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Student'},
        ),
        migrations.AddField(
            model_name='student',
            name='batch_year',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='dateOfBirth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='homeAddress',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='major',
            field=models.CharField(blank=True, choices=[('M', 'Morning'), ('A', 'Afternoon')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.CharField(blank=True, choices=[('M', 'Morning'), ('A', 'Afternoon')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='telephone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
