# Generated by Django 3.2.5 on 2022-06-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20220621_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='major',
            field=models.CharField(blank=True, choices=[('SE', 'Software Engineer'), ('CS', 'Computer Science'), ('IT', 'Information Technology')], max_length=2, null=True),
        ),
    ]
